'use client';
import {useEffect,useState} from 'react';
import {categories} from '../../lib/catalogue';
type Photo={url:string;caption:string};
export default function CategoryPictures(){const [names,setNames]=useState(categories.map(c=>c.name)),[category,setCategory]=useState(categories[0].name),[gallery,setGallery]=useState<Record<string,Photo[]>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>{fetch('/api/catalogue').then(r=>r.json()).then((d:any)=>{setNames(d.categories.map((c:any)=>c.name));setGallery(d.gallery||{})}).catch(()=>setMessage('Unable to load category pictures. Please reload.'))},[]);
async function upload(e:React.FormEvent<HTMLFormElement>,slot:number){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);data.set('category',category);data.set('slot',String(slot));setBusy(true);setMessage('Uploading picture…');try{const r=await fetch('/api/admin/pictures',{method:'POST',body:data});const d:any=await r.json();if(!r.ok)throw Error(d.error);setGallery(g=>({...g,[category]:d.photos}));setMessage('Picture saved. It is now visible in the product category.');form.reset()}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Please try again.')}finally{setBusy(false)}}
async function remove(slot:number){setBusy(true);try{const r=await fetch('/api/admin/pictures',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({category,slot})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setGallery(g=>({...g,[category]:d.photos}));setMessage('Picture removed from the category.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to remove picture.')}finally{setBusy(false)}}
const photos=gallery[category]||[];return <section className="picture-manager"><h2>Category product pictures</h2><p>Add at least three pictures to each category. You can add up to 12. Upload JPEG, PNG or WebP files, up to 5 MB each.</p><label>Choose a category<select disabled={busy} value={category} onChange={e=>setCategory(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></label><p role="status">{message}</p><div className="picture-slots">{Array.from({length:Math.max(3,Math.min(12,photos.length+1))},(_,i)=><form className="picture-slot" key={`${category}-${i}`} onSubmit={e=>upload(e,i)}><h3>Picture {i+1}</h3>{photos[i]?<img src={photos[i].url} alt={photos[i].caption||`${category} product`}/>:<div className="picture-placeholder">Add a product picture</div>}<label>Product name / caption<input name="caption" maxLength={120} defaultValue={photos[i]?.caption||''}/></label><label>{photos[i]?'Replace picture':'Choose picture'}<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required disabled={busy}/></label><button className="button primary" disabled={busy}>{photos[i]?'Replace picture':'Upload picture'}</button>{photos[i]&&<button type="button" className="button secondary" disabled={busy} onClick={()=>remove(i)}>Remove</button>}</form>)}</div></section>}

